2025-08-11 14:46:35,736 - INFO - Running strategy for /MES at 2025-08-11 07:46:35.736479-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 14:46:35,738 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 14:46:35,739 - ERROR - Error in strategy for /MES: get_time_based_historical_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 385, in get_historical_and_live_data
    df = get_historical_data(ticker, timeframe, logger, strategy)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 94, in get_historical_data
    return get_time_based_historical_data(ticker, timeframe, logger, db_api_key, dataset, strategy)
TypeError: get_time_based_historical_data() takes 5 positional arguments but 6 were given
2025-08-11 14:46:36,945 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 15:10:27,775 - INFO - Running strategy for /MES at 2025-08-11 08:10:27.775512-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 15:10:27,776 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 15:10:27,776 - ERROR - Error in strategy for /MES: get_time_based_historical_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 228, in get_historical_and_live_data
    df = get_historical_data(ticker, timeframe, logger, strategy)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 50, in get_historical_data
    return get_time_based_historical_data(ticker, timeframe, logger, db_api_key, dataset, strategy)
TypeError: get_time_based_historical_data() takes 5 positional arguments but 6 were given
2025-08-11 15:10:28,851 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 15:14:52,543 - INFO - Running strategy for /MES at 2025-08-11 08:14:52.543399-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 15:14:52,545 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 15:14:52,545 - ERROR - Error in strategy for /MES: get_time_based_historical_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 228, in get_historical_and_live_data
    df = get_historical_data(ticker, timeframe, logger, strategy)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 50, in get_historical_data
    return get_time_based_historical_data(ticker, timeframe, logger, db_api_key, dataset, strategy)
TypeError: get_time_based_historical_data() takes 5 positional arguments but 6 were given
2025-08-11 15:14:53,358 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 18:16:59,433 - INFO - Running strategy for /MES at 2025-08-11 11:16:59.433714-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 18:16:59,517 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 18:16:59,580 - ERROR - Error in strategy for /MES: get_time_based_historical_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 298, in get_historical_and_live_data
    return get_time_based_historical_data(
        ticker, timeframe, logger, db_api_key, dataset, strategy
    )
TypeError: get_time_based_historical_data() takes 5 positional arguments but 6 were given
2025-08-11 18:17:00,602 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 20:02:11,847 - INFO - Running strategy for /MES at 2025-08-11 13:02:11.847678-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 20:02:11,849 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 20:02:16,421 - INFO - Resolved symbol: {'result': {'MESU5': [{'d0': '2025-08-06', 'd1': '2025-08-12', 's': '42002651'}]}, 'symbols': ['MESU5'], 'stype_in': 'raw_symbol', 'stype_out': 'instrument_id', 'start_date': '2025-08-06', 'end_date': '2025-08-12', 'partial': [], 'not_found': [], 'message': 'OK', 'status': 0}
2025-08-11 20:02:40,306 - INFO - Created 828 5 bars for /MES
2025-08-11 20:02:40,499 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 20:05:48,086 - INFO - Running strategy for /MES at 2025-08-11 13:05:48.086957-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 20:05:48,087 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 20:05:48,088 - ERROR - Error in strategy for /MES: cannot access local variable 'df' where it is not associated with a value
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 342, in get_historical_and_live_data
    if df is not None:
       ^^
UnboundLocalError: cannot access local variable 'df' where it is not associated with a value
2025-08-11 20:05:48,759 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 20:06:11,280 - INFO - Running strategy for /MES at 2025-08-11 13:06:11.280863-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 20:06:11,281 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 20:06:11,281 - ERROR - Error in strategy for /MES: cannot access local variable 'df' where it is not associated with a value
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 342, in get_historical_and_live_data
    if df is not None:
       ^^
UnboundLocalError: cannot access local variable 'df' where it is not associated with a value
2025-08-11 20:06:12,041 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:18:22,169 - INFO - Running strategy for /MES at 2025-08-11 14:18:22.169839-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:18:25,042 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:20:17,917 - INFO - Running strategy for /MES at 2025-08-11 14:20:17.917350-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:20:19,771 - ERROR - Error in strategy for /MES: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 82, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 57, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:20:19,927 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:20:34,651 - INFO - Running strategy for /MES at 2025-08-11 14:20:34.651255-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:20:34,651 - INFO - Running strategy for /MES at 2025-08-11 14:20:34.651255-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:20:37,466 - ERROR - Error in strategy for /MES: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 82, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 57, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:20:37,466 - ERROR - Error in strategy for /MES: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 82, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 57, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:20:37,794 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:20:37,794 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:21:03,353 - INFO - Running strategy for /MES at 2025-08-11 14:21:03.353062-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:21:06,016 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:21:30,710 - INFO - Running strategy for /MES at 2025-08-11 14:21:30.710391-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:21:32,756 - ERROR - Error in strategy for /MES: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 82, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 57, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:21:32,959 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:33:00,583 - INFO - Running strategy for /MES at 2025-08-11 14:33:00.583688-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:33:04,054 - ERROR - Error in strategy for /MES: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 98, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 87, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 58, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:33:04,203 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:33:33,422 - INFO - Running strategy for /MES at 2025-08-11 14:33:33.422603-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:33:35,423 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:34:25,084 - INFO - Running strategy for /MES at 2025-08-11 14:34:25.084933-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:34:28,610 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:34:58,454 - INFO - Running strategy for /MES at 2025-08-11 14:34:58.454600-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:35:01,706 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:35:38,195 - INFO - Running strategy for /MES at 2025-08-11 14:35:38.195731-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:35:41,399 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:36:04,940 - INFO - Running strategy for /MES at 2025-08-11 14:36:04.940243-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:36:07,823 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:37:18,282 - INFO - Running strategy for /MES at 2025-08-11 14:37:18.282730-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:37:21,199 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:38:23,656 - INFO - Running strategy for /MES at 2025-08-11 14:38:23.656860-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:38:26,533 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:38:44,311 - INFO - Running strategy for /MES at 2025-08-11 14:38:44.311229-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:38:47,279 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:39:11,030 - INFO - Running strategy for /MES at 2025-08-11 14:39:11.030400-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:39:12,959 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:41:42,566 - INFO - Running strategy for /MES at 2025-08-11 14:41:42.565967-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:41:45,577 - ERROR - Error in strategy for /MES: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 99, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 88, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 58, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:41:45,861 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:43:31,653 - INFO - Running strategy for /MES at 2025-08-11 14:43:31.653445-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:43:35,922 - ERROR - Error in strategy for /MES: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 100, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 89, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 58, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:43:36,075 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:45:49,972 - INFO - Running strategy for /MES at 2025-08-11 14:45:49.972505-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:45:52,626 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:48:07,773 - INFO - Running strategy for /MES at 2025-08-11 14:48:07.773743-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:48:10,563 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:51:24,931 - INFO - Running strategy for /MES at 2025-08-11 14:51:24.931021-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:51:27,769 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:53:18,407 - INFO - Running strategy for /MES at 2025-08-11 14:53:18.407711-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:53:20,715 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:55:16,794 - INFO - Running strategy for /MES at 2025-08-11 14:55:16.794345-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:55:19,219 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:56:30,188 - INFO - Running strategy for /MES at 2025-08-11 14:56:30.188424-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:56:32,410 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:01:22,035 - INFO - Running strategy for /MES at 2025-08-11 15:01:22.035257-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:01:24,254 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:01:44,201 - INFO - Running strategy for /MES at 2025-08-11 15:01:44.201513-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:01:47,615 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:02:01,841 - INFO - Running strategy for /MES at 2025-08-11 15:02:01.841455-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:02:04,476 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:04:14,458 - INFO - Running strategy for /MES at 2025-08-11 15:04:14.458850-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:04:17,006 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:04:48,923 - INFO - Running strategy for /MES at 2025-08-11 15:04:48.923456-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:04:53,534 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:27:17,854 - INFO - Running strategy for /MES at 2025-08-11 15:27:17.854350-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:27:22,683 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:32:20,877 - INFO - Running strategy for /MES at 2025-08-11 15:32:20.877747-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:32:24,009 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:36:15,077 - INFO - Running strategy for /MES at 2025-08-11 15:36:15.077590-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:36:18,465 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:37:53,930 - INFO - Running strategy for /MES at 2025-08-11 15:37:53.930141-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:37:58,644 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:04:07,306 - INFO - Running strategy for /MES at 2025-08-11 16:04:07.306069-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:04:12,825 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:04:42,588 - INFO - Running strategy for /MES at 2025-08-11 16:04:42.588458-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:05:09,562 - INFO - Running strategy for /MES at 2025-08-11 16:05:09.562166-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:05:24,465 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:05:56,502 - INFO - Running strategy for /MES at 2025-08-11 16:05:56.502882-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:06:53,162 - ERROR - Error fetching historical end time for dataset GLBX.MDP3: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-08-11 23:06:53,162 - ERROR - Error in strategy for /MES: name 'datetime' is not defined
Traceback (most recent call last):
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 460, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 504, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\truststore\_api.py", line 113, in wrap_socket
    ssl_sock = self._ctx.wrap_socket(
        sock,
    ...<4 lines>...
        session=session,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 460, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 504, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\truststore\_api.py", line 113, in wrap_socket
    ssl_sock = self._ctx.wrap_socket(
        sock,
    ...<4 lines>...
        session=session,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 42, in get_historical_end_time
    metadata = DATABENTO_CLIENT.metadata.get_dataset_range(dataset=dataset)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\metadata.py", line 254, in get_dataset_range
    response: Response = self._get(
                         ~~~~~~~~~^
        url=self._base_url + ".get_dataset_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        params=params,
        ^^^^^^^^^^^^^^
        basic_auth=True,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 61, in _get
    with requests.get(
         ~~~~~~~~~~~~^
        url=url,
        ^^^^^^^^
    ...<3 lines>...
        timeout=(self.TIMEOUT, self.TIMEOUT),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as response:
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 120, in get_historical_and_live_data
    def get_historical_and_live_data(ticker, timeframe, logger, strategy):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 108, in get_historical_data
    end_time = get_historical_end_time(dataset, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 51, in get_historical_end_time
    safe_historical_end = datetime.now(timezone.utc) - timedelta(minutes=10)
                          ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'?
2025-08-11 23:09:55,897 - INFO - Running strategy for /MES at 2025-08-11 16:09:55.897505-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:09:58,692 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:11:14,072 - INFO - Running strategy for /MES at 2025-08-11 16:11:14.072266-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:11:17,860 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:14:12,011 - INFO - Running strategy for /MES at 2025-08-11 16:14:12.011334-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:14:14,897 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:20:26,407 - INFO - Running strategy for /MES at 2025-08-11 16:20:26.407543-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:20:28,441 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:30:48,441 - INFO - Running strategy for /MES at 2025-08-11 16:30:48.441092-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:30:52,906 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:58:03,396 - INFO - Running strategy for /MES at 2025-08-11 16:58:03.396106-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:58:05,498 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:58:45,996 - INFO - Running strategy for /MES at 2025-08-11 16:58:45.996719-04:00 with params: Schwab_QTY=3, Tasty_QTY=20 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:58:48,415 - ERROR - Error in main loop for /MES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
