2025-08-11 14:46:35,734 - INFO - Running strategy for NVDA at 2025-08-11 07:46:35.734564-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 14:46:35,735 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 14:46:35,736 - ERROR - Error in strategy for NVDA: get_time_based_historical_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 385, in get_historical_and_live_data
    df = get_historical_data(ticker, timeframe, logger, strategy)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 94, in get_historical_data
    return get_time_based_historical_data(ticker, timeframe, logger, db_api_key, dataset, strategy)
TypeError: get_time_based_historical_data() takes 5 positional arguments but 6 were given
2025-08-11 15:10:27,773 - INFO - Running strategy for NVDA at 2025-08-11 08:10:27.773684-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 15:10:27,774 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 15:10:27,774 - ERROR - Error in strategy for NVDA: get_time_based_historical_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 228, in get_historical_and_live_data
    df = get_historical_data(ticker, timeframe, logger, strategy)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 50, in get_historical_data
    return get_time_based_historical_data(ticker, timeframe, logger, db_api_key, dataset, strategy)
TypeError: get_time_based_historical_data() takes 5 positional arguments but 6 were given
2025-08-11 15:14:52,541 - INFO - Running strategy for NVDA at 2025-08-11 08:14:52.541603-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 15:14:52,542 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 15:14:52,543 - ERROR - Error in strategy for NVDA: get_time_based_historical_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 228, in get_historical_and_live_data
    df = get_historical_data(ticker, timeframe, logger, strategy)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 50, in get_historical_data
    return get_time_based_historical_data(ticker, timeframe, logger, db_api_key, dataset, strategy)
TypeError: get_time_based_historical_data() takes 5 positional arguments but 6 were given
2025-08-11 18:16:59,431 - INFO - Running strategy for NVDA at 2025-08-11 11:16:59.431491-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 18:16:59,432 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 18:16:59,433 - ERROR - Error in strategy for NVDA: get_time_based_historical_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 298, in get_historical_and_live_data
    return get_time_based_historical_data(
        ticker, timeframe, logger, db_api_key, dataset, strategy
    )
TypeError: get_time_based_historical_data() takes 5 positional arguments but 6 were given
2025-08-11 18:17:01,249 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 20:02:11,843 - INFO - Running strategy for NVDA at 2025-08-11 13:02:11.843846-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 20:02:11,848 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 20:02:14,625 - INFO - Resolved symbol: {'result': {'NVDA': [{'d0': '2025-08-06', 'd1': '2025-08-09', 's': '11667'}, {'d0': '2025-08-11', 'd1': '2025-08-12', 's': '11667'}]}, 'symbols': ['NVDA'], 'stype_in': 'raw_symbol', 'stype_out': 'instrument_id', 'start_date': '2025-08-06', 'end_date': '2025-08-12', 'partial': ['NVDA'], 'not_found': [], 'message': 'Partially resolved', 'status': 1}
2025-08-11 20:02:31,644 - INFO - Created 576 5 bars for NVDA
2025-08-11 20:02:32,202 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 20:05:48,086 - INFO - Running strategy for NVDA at 2025-08-11 13:05:48.086443-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 20:05:48,087 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 20:05:48,087 - ERROR - Error in strategy for NVDA: cannot access local variable 'df' where it is not associated with a value
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 342, in get_historical_and_live_data
    if df is not None:
       ^^
UnboundLocalError: cannot access local variable 'df' where it is not associated with a value
2025-08-11 20:05:49,153 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 20:06:11,278 - INFO - Running strategy for NVDA at 2025-08-11 13:06:11.278952-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 20:06:11,279 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 20:06:11,279 - ERROR - Error in strategy for NVDA: cannot access local variable 'df' where it is not associated with a value
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 342, in get_historical_and_live_data
    if df is not None:
       ^^
UnboundLocalError: cannot access local variable 'df' where it is not associated with a value
2025-08-11 20:06:12,392 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:18:22,165 - INFO - Running strategy for NVDA at 2025-08-11 14:18:22.164982-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:18:25,420 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:20:17,916 - INFO - Running strategy for NVDA at 2025-08-11 14:20:17.916821-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:20:19,245 - ERROR - Error in strategy for NVDA: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 82, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 57, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:20:19,610 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:20:34,650 - INFO - Running strategy for NVDA at 2025-08-11 14:20:34.650920-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:20:34,650 - INFO - Running strategy for NVDA at 2025-08-11 14:20:34.650920-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:20:37,383 - ERROR - Error in strategy for NVDA: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 82, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 57, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:20:37,383 - ERROR - Error in strategy for NVDA: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 82, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 57, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:20:38,010 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:20:38,010 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:21:03,341 - INFO - Running strategy for NVDA at 2025-08-11 14:21:03.341669-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:21:05,241 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:21:30,711 - INFO - Running strategy for NVDA at 2025-08-11 14:21:30.711929-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:21:32,051 - ERROR - Error in strategy for NVDA: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 82, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 57, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:21:32,394 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:33:00,583 - INFO - Running strategy for NVDA at 2025-08-11 14:33:00.583252-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:33:02,573 - ERROR - Error in strategy for NVDA: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 98, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 87, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 58, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:33:03,413 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:33:33,420 - INFO - Running strategy for NVDA at 2025-08-11 14:33:33.420673-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:33:36,427 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:34:25,082 - INFO - Running strategy for NVDA at 2025-08-11 14:34:25.082532-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:34:28,762 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:34:58,450 - INFO - Running strategy for NVDA at 2025-08-11 14:34:58.450628-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:35:00,565 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:35:38,190 - INFO - Running strategy for NVDA at 2025-08-11 14:35:38.189989-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:35:40,154 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:36:04,938 - INFO - Running strategy for NVDA at 2025-08-11 14:36:04.938528-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:36:06,840 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:37:18,277 - INFO - Running strategy for NVDA at 2025-08-11 14:37:18.277243-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:37:21,134 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:38:23,652 - INFO - Running strategy for NVDA at 2025-08-11 14:38:23.652126-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:38:26,177 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:38:44,309 - INFO - Running strategy for NVDA at 2025-08-11 14:38:44.309668-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:38:47,355 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:39:11,025 - INFO - Running strategy for NVDA at 2025-08-11 14:39:11.025645-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:39:12,916 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:41:42,564 - INFO - Running strategy for NVDA at 2025-08-11 14:41:42.564742-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:41:44,436 - ERROR - Error in strategy for NVDA: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 99, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 88, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 58, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:41:44,762 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:43:31,652 - INFO - Running strategy for NVDA at 2025-08-11 14:43:31.652936-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:43:33,333 - ERROR - Error in strategy for NVDA: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 100, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 89, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 58, in get_historical_start_time
    start_time = (end_time - timedelta(days=5)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:43:33,664 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:45:49,966 - INFO - Running strategy for NVDA at 2025-08-11 14:45:49.966542-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:45:52,558 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:48:07,773 - INFO - Running strategy for NVDA at 2025-08-11 14:48:07.773405-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:48:10,242 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:51:24,927 - INFO - Running strategy for NVDA at 2025-08-11 14:51:24.927578-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:51:26,878 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:53:18,403 - INFO - Running strategy for NVDA at 2025-08-11 14:53:18.403358-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:53:20,785 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:55:16,795 - INFO - Running strategy for NVDA at 2025-08-11 14:55:16.795115-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:55:23,493 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:56:30,184 - INFO - Running strategy for NVDA at 2025-08-11 14:56:30.184659-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:56:32,747 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:01:22,031 - INFO - Running strategy for NVDA at 2025-08-11 15:01:22.031898-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:01:24,110 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:01:44,193 - INFO - Running strategy for NVDA at 2025-08-11 15:01:44.193325-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:01:46,417 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:02:01,837 - INFO - Running strategy for NVDA at 2025-08-11 15:02:01.837242-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:02:04,707 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:04:14,457 - INFO - Running strategy for NVDA at 2025-08-11 15:04:14.457469-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:04:16,962 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:04:48,919 - INFO - Running strategy for NVDA at 2025-08-11 15:04:48.919722-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:04:51,570 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:27:17,854 - INFO - Running strategy for NVDA at 2025-08-11 15:27:17.854116-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:27:21,540 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:32:20,877 - INFO - Running strategy for NVDA at 2025-08-11 15:32:20.877642-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:32:22,871 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:36:15,077 - INFO - Running strategy for NVDA at 2025-08-11 15:36:15.077019-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:36:17,361 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:37:53,927 - INFO - Running strategy for NVDA at 2025-08-11 15:37:53.927669-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:37:56,871 - ERROR - Error in main loop for NVDA: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 60, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:04:07,304 - INFO - Running strategy for NVDA at 2025-08-11 16:04:07.304733-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:04:10,957 - INFO - Market closed
2025-08-11 23:04:10,958 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:04:42,585 - INFO - Running strategy for NVDA at 2025-08-11 16:04:42.585699-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:05:09,560 - INFO - Running strategy for NVDA at 2025-08-11 16:05:09.560093-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:05:15,857 - INFO - Market closed
2025-08-11 23:05:15,857 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:05:56,497 - INFO - Running strategy for NVDA at 2025-08-11 16:05:56.497465-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:06:53,161 - ERROR - Error fetching historical end time for dataset XNAS.ITCH: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-08-11 23:06:53,162 - ERROR - Error in strategy for NVDA: name 'datetime' is not defined
Traceback (most recent call last):
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 460, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 504, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\truststore\_api.py", line 113, in wrap_socket
    ssl_sock = self._ctx.wrap_socket(
        sock,
    ...<4 lines>...
        session=session,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 460, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 504, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\truststore\_api.py", line 113, in wrap_socket
    ssl_sock = self._ctx.wrap_socket(
        sock,
    ...<4 lines>...
        session=session,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 42, in get_historical_end_time
    metadata = DATABENTO_CLIENT.metadata.get_dataset_range(dataset=dataset)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\metadata.py", line 254, in get_dataset_range
    response: Response = self._get(
                         ~~~~~~~~~^
        url=self._base_url + ".get_dataset_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        params=params,
        ^^^^^^^^^^^^^^
        basic_auth=True,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 61, in _get
    with requests.get(
         ~~~~~~~~~~~~^
        url=url,
        ^^^^^^^^
    ...<3 lines>...
        timeout=(self.TIMEOUT, self.TIMEOUT),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as response:
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 120, in get_historical_and_live_data
    def get_historical_and_live_data(ticker, timeframe, logger, strategy):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 108, in get_historical_data
    end_time = get_historical_end_time(dataset, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 51, in get_historical_end_time
    safe_historical_end = datetime.now(timezone.utc) - timedelta(minutes=10)
                          ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'?
2025-08-11 23:09:55,895 - INFO - Running strategy for NVDA at 2025-08-11 16:09:55.895830-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:09:58,727 - INFO - Market closed
2025-08-11 23:09:58,728 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:11:14,071 - INFO - Running strategy for NVDA at 2025-08-11 16:11:14.071930-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:11:16,318 - INFO - Market closed
2025-08-11 23:11:16,318 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:14:12,008 - INFO - Running strategy for NVDA at 2025-08-11 16:14:12.008658-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:14:15,713 - INFO - Market closed
2025-08-11 23:14:15,714 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:20:26,402 - INFO - Running strategy for NVDA at 2025-08-11 16:20:26.402263-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:20:28,139 - INFO - Market closed
2025-08-11 23:20:28,139 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:30:48,438 - INFO - Running strategy for NVDA at 2025-08-11 16:30:48.438174-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:30:50,227 - INFO - Market closed
2025-08-11 23:30:50,228 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:58:03,394 - INFO - Running strategy for NVDA at 2025-08-11 16:58:03.393991-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:58:05,204 - INFO - Market closed
2025-08-11 23:58:05,204 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:58:45,994 - INFO - Running strategy for NVDA at 2025-08-11 16:58:45.994730-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:58:48,021 - INFO - Market closed
2025-08-11 23:58:48,021 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
    ~~~~~~~~~~^^^^^^^^
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:07:48,663 - INFO - Running strategy for NVDA at 2025-08-11 17:07:48.663607-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:07:50,402 - INFO - Market closed
2025-08-11 23:07:50,402 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:13:41,322 - INFO - Running strategy for NVDA at 2025-08-11 17:13:41.322448-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:13:43,440 - INFO - Market closed
2025-08-11 23:13:43,440 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:14:59,091 - INFO - Running strategy for NVDA at 2025-08-11 17:14:59.091111-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:15:00,568 - INFO - Market closed
2025-08-11 23:15:00,611 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:20:24,429 - INFO - Running strategy for NVDA at 2025-08-11 17:20:24.429531-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:20:26,192 - INFO - Market closed
2025-08-11 23:20:26,192 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:25:13,384 - INFO - Running strategy for NVDA at 2025-08-11 17:25:13.384870-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:25:14,904 - INFO - Market closed
2025-08-11 23:25:14,917 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:48:28,883 - INFO - Running strategy for NVDA at 2025-08-11 17:48:28.883158-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:48:29,839 - INFO - Market closed
2025-08-11 23:48:29,839 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:51:36,966 - INFO - Running strategy for NVDA at 2025-08-11 17:51:36.966848-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:51:37,933 - INFO - Market closed
2025-08-11 23:51:37,933 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:55:15,737 - INFO - Running strategy for NVDA at 2025-08-11 17:55:15.737305-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:55:18,180 - INFO - Market closed
2025-08-11 23:55:18,180 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:56:15,526 - INFO - Running strategy for NVDA at 2025-08-11 17:56:15.526470-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:56:18,868 - INFO - Market closed
2025-08-11 23:56:18,869 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-11 23:59:16,532 - INFO - Running strategy for NVDA at 2025-08-11 17:59:16.532046-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:59:20,458 - INFO - Market closed
2025-08-11 23:59:20,459 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 00:01:01,688 - INFO - Running strategy for NVDA at 2025-08-11 18:01:01.688056-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 00:01:06,371 - INFO - Market closed
2025-08-12 00:01:06,371 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 00:05:05,038 - INFO - Running strategy for NVDA at 2025-08-11 18:05:05.038774-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 00:05:10,846 - INFO - Market closed
2025-08-12 00:05:10,846 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 00:18:36,447 - INFO - Running strategy for NVDA at 2025-08-11 18:18:36.447456-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 00:18:37,237 - ERROR - Error in strategy for NVDA: get_tick_based_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 136, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 130, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, instrument_id, symbol)
TypeError: get_tick_based_data() takes 5 positional arguments but 6 were given
2025-08-12 00:18:37,960 - INFO - Market closed
2025-08-12 00:18:37,961 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 00:19:32,043 - INFO - Running strategy for NVDA at 2025-08-11 18:19:32.043539-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 00:19:33,135 - ERROR - Error in strategy for NVDA: get_tick_based_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 136, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 130, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, instrument_id, symbol)
TypeError: get_tick_based_data() takes 5 positional arguments but 6 were given
2025-08-12 00:19:34,302 - INFO - Market closed
2025-08-12 00:19:34,302 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 00:20:46,446 - INFO - Running strategy for NVDA at 2025-08-11 18:20:46.446268-04:00 with params: Schwab_QTY=4, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 00:20:48,051 - ERROR - Error in strategy for NVDA: get_tick_based_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 136, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 130, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, instrument_id, symbol)
TypeError: get_tick_based_data() takes 5 positional arguments but 6 were given
2025-08-12 00:20:49,781 - INFO - Market closed
2025-08-12 00:20:49,781 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:05:19,226 - INFO - Running strategy for NVDA at 2025-08-11 21:05:19.226601-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:05:19,227 - ERROR - Error in strategy for NVDA: 'months' is an invalid keyword argument for __new__()
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 115, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 100, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 74, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
TypeError: 'months' is an invalid keyword argument for __new__()
2025-08-12 03:05:19,687 - INFO - Market closed
2025-08-12 03:05:19,687 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:08:06,174 - INFO - Running strategy for NVDA at 2025-08-11 21:08:06.174671-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:08:06,175 - ERROR - Error in strategy for NVDA: 'months' is an invalid keyword argument for __new__()
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 115, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 100, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 74, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
TypeError: 'months' is an invalid keyword argument for __new__()
2025-08-12 03:08:06,625 - INFO - Market closed
2025-08-12 03:08:06,625 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:10:55,152 - INFO - Running strategy for NVDA at 2025-08-11 21:10:55.152186-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:10:55,153 - ERROR - Error in strategy for NVDA: 'months' is an invalid keyword argument for __new__()
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 117, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 102, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 74, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
TypeError: 'months' is an invalid keyword argument for __new__()
2025-08-12 03:10:55,605 - INFO - Market closed
2025-08-12 03:10:55,605 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:12:16,325 - INFO - Running strategy for NVDA at 2025-08-11 21:12:16.325162-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:12:16,325 - ERROR - Error in strategy for NVDA: 'months' is an invalid keyword argument for __new__()
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 117, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 102, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 74, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
TypeError: 'months' is an invalid keyword argument for __new__()
2025-08-12 03:12:16,871 - INFO - Market closed
2025-08-12 03:12:16,871 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:15:58,311 - INFO - Running strategy for NVDA at 2025-08-11 21:15:58.311468-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:15:58,311 - ERROR - Error in strategy for NVDA: 'months' is an invalid keyword argument for __new__()
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 117, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 102, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 74, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
TypeError: 'months' is an invalid keyword argument for __new__()
2025-08-12 03:15:58,811 - INFO - Market closed
2025-08-12 03:15:58,811 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:16:25,712 - INFO - Running strategy for NVDA at 2025-08-11 21:16:25.712302-04:00 with params: Schwab_QTY=0, Tasty_QTY=2 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:16:25,712 - INFO - Running strategy for NVDA at 2025-08-11 21:16:25.712302-04:00 with params: Schwab_QTY=0, Tasty_QTY=2 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:16:25,713 - ERROR - Error in strategy for NVDA: 'months' is an invalid keyword argument for __new__()
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 117, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 102, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 74, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
TypeError: 'months' is an invalid keyword argument for __new__()
2025-08-12 03:16:25,713 - ERROR - Error in strategy for NVDA: 'months' is an invalid keyword argument for __new__()
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 117, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 102, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 74, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
TypeError: 'months' is an invalid keyword argument for __new__()
2025-08-12 03:16:26,317 - INFO - Market closed
2025-08-12 03:16:26,317 - INFO - Market closed
2025-08-12 03:16:26,317 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:16:26,317 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:16:54,252 - INFO - Running strategy for NVDA at 2025-08-11 21:16:54.252442-04:00 with params: Schwab_QTY=0, Tasty_QTY=2 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:16:54,252 - ERROR - Error in strategy for NVDA: 'months' is an invalid keyword argument for __new__()
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 117, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 102, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 74, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
TypeError: 'months' is an invalid keyword argument for __new__()
2025-08-12 03:16:54,829 - INFO - Market closed
2025-08-12 03:16:54,829 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:17:35,486 - INFO - Running strategy for NVDA at 2025-08-11 21:17:35.486176-04:00 with params: Schwab_QTY=0, Tasty_QTY=2 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:17:35,487 - ERROR - Error in strategy for NVDA: 'months' is an invalid keyword argument for __new__()
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 119, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 104, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 74, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
TypeError: 'months' is an invalid keyword argument for __new__()
2025-08-12 03:17:36,034 - INFO - Market closed
2025-08-12 03:17:36,034 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:18:18,846 - INFO - Running strategy for NVDA at 2025-08-11 21:18:18.846095-04:00 with params: Schwab_QTY=0, Tasty_QTY=2 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:18:18,846 - ERROR - Error in strategy for NVDA: 'months' is an invalid keyword argument for __new__()
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 118, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 103, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 74, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
TypeError: 'months' is an invalid keyword argument for __new__()
2025-08-12 03:18:19,480 - INFO - Market closed
2025-08-12 03:18:19,480 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:19:10,864 - INFO - Running strategy for NVDA at 2025-08-11 21:19:10.864311-04:00 with params: Schwab_QTY=0, Tasty_QTY=2 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:19:10,865 - ERROR - Error in strategy for NVDA: 'months' is an invalid keyword argument for __new__()
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 118, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 102, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 74, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
TypeError: 'months' is an invalid keyword argument for __new__()
2025-08-12 03:19:11,354 - INFO - Market closed
2025-08-12 03:19:11,354 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:20:30,175 - INFO - Running strategy for NVDA at 2025-08-11 21:20:30.175079-04:00 with params: Schwab_QTY=0, Tasty_QTY=2 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:20:30,177 - ERROR - Error in strategy for NVDA: 'months' is an invalid keyword argument for __new__()
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 119, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 103, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 75, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
TypeError: 'months' is an invalid keyword argument for __new__()
2025-08-12 03:20:30,775 - INFO - Market closed
2025-08-12 03:20:30,775 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:21:17,443 - INFO - Running strategy for NVDA at 2025-08-11 21:21:17.443525-04:00 with params: Schwab_QTY=0, Tasty_QTY=2 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:21:17,444 - ERROR - Error in strategy for NVDA: 'months' is an invalid keyword argument for __new__()
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 121, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 105, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 75, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
TypeError: 'months' is an invalid keyword argument for __new__()
2025-08-12 03:21:18,024 - INFO - Market closed
2025-08-12 03:21:18,024 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:22:57,875 - INFO - Running strategy for NVDA at 2025-08-11 21:22:57.875895-04:00 with params: Schwab_QTY=0, Tasty_QTY=2 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:22:57,876 - ERROR - Error in strategy for NVDA: 'months' is an invalid keyword argument for __new__()
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 120, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 104, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 75, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
TypeError: 'months' is an invalid keyword argument for __new__()
2025-08-12 03:22:58,347 - INFO - Market closed
2025-08-12 03:22:58,347 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:25:17,626 - INFO - Running strategy for NVDA at 2025-08-11 21:25:17.625077-04:00 with params: Schwab_QTY=0, Tasty_QTY=2 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:25:17,626 - ERROR - Error in strategy for NVDA: 'months' is an invalid keyword argument for __new__()
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 121, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 105, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 76, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
TypeError: 'months' is an invalid keyword argument for __new__()
2025-08-12 03:25:18,071 - INFO - Market closed
2025-08-12 03:25:18,071 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:25:59,449 - INFO - Running strategy for NVDA at 2025-08-11 21:25:59.449761-04:00 with params: Schwab_QTY=0, Tasty_QTY=2 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:25:59,449 - ERROR - Error in strategy for NVDA: 'months' is an invalid keyword argument for __new__()
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 121, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 105, in get_historical_data
    start_time = get_historical_start_time(ticker, timeframe, end_time)
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 75, in get_historical_start_time
    start_time = end_time - timedelta(months=1)
TypeError: 'months' is an invalid keyword argument for __new__()
2025-08-12 03:25:59,912 - INFO - Market closed
2025-08-12 03:25:59,913 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:27:14,843 - INFO - Running strategy for NVDA at 2025-08-11 21:27:14.843319-04:00 with params: Schwab_QTY=0, Tasty_QTY=2 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:29:11,827 - INFO - Running strategy for NVDA at 2025-08-11 21:29:11.827338-04:00 with params: Schwab_QTY=0, Tasty_QTY=2 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:29:13,412 - INFO - Market closed
2025-08-12 03:29:13,412 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
2025-08-12 03:30:28,544 - INFO - Running strategy for NVDA at 2025-08-11 21:30:28.544212-04:00 with params: Schwab_QTY=0, Tasty_QTY=2 TRENDS=(1, EMA), (1, EMA)
2025-08-12 03:31:19,807 - INFO - Market closed
2025-08-12 03:31:19,807 - ERROR - Error in main loop for NVDA: store_logs() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 67, in main_strategy_loop
    store_logs(ticker)
TypeError: store_logs() missing 1 required positional argument: 'strategy'
